### ISSUE TITLE
AS Information not available

### ISSUE THREAD

**Issue by alxhrck** [opendns/pyinvestigate#4]
It doesn't appear that this module supports querying the AS information endpoint as described by the documentation.

https://docs.opendns.com/developer/investigate-api/as-information-for-a-domain/

**Comment by dead10ck** [comment]
Merged your PR. Thanks for that! I will post here and close out the issue when it's released to PyPI.

**Comment by dead10ck** [comment]
This has been published to PyPI in version 1.2.4. Thanks again!
